### ISSUE TITLE
Ogg #6-- Microscope Essentials to Microscope Accessories

### ISSUE THREAD

**Issue by stephenogg** [WU-BIMAC/NBOMicroscopyMetadataSpecs#43]
**Current Hardware Category Name:** MicroscopeEssentials <br/>

**Brief description of the change and its rationale (short and compelling):**
The items in this category, environmental chamber and table, are not essential, they are accessories 

**New Category name:**  MicroscopeAccessories

**Comment by strambc** [comment]
Makes sense.
Will be done!

**Comment by strambc** [comment]
Was dealt with for v1.00 of Micro-Meta App
https://github.com/WU-BIMAC/MicroMetaApp-React/issues/371
